-- ArenaCoach/KillTargets.lua
-- СГЕНЕРИРОВАНО tools/gen_addon_killtargets.py — не редактировать руками.
-- Источник: kb/drafts + kb/matchups (frontmatter kill_target.primary).
--
-- Ключ: "<bracket>|<наши классы>|<классы врагов>", классы sorted+lowercase —
-- ровно то, что аддон собирает сам из UnitClass на воротах.
-- Значение: { t = "КЛАСС ЦЕЛИ", sure = true|false }.
-- sure = false — KB-документы под этим ключом расходятся (схлопывание спеков
-- в классы), цель показываем как предположение.

local AC = ArenaCoach

AC.KB_KILL_TARGETS = {
    ["2v2|druid+rogue|druid+hunter"] = { t = "HUNTER", sure = true },
    ["2v2|druid+rogue|druid+rogue"] = { t = "DRUID", sure = true },
    ["2v2|druid+rogue|druid+warlock"] = { t = "DRUID", sure = true },
    ["2v2|druid+rogue|druid+warrior"] = { t = "DRUID", sure = true },
    ["2v2|druid+rogue|mage+priest"] = { t = "MAGE", sure = true },
    ["2v2|druid+rogue|mage+rogue"] = { t = "MAGE", sure = true },
    ["2v2|druid+rogue|paladin+shaman"] = { t = "SHAMAN", sure = true },
    ["2v2|druid+rogue|paladin+warrior"] = { t = "WARRIOR", sure = true },
    ["2v2|druid+rogue|priest+rogue"] = { t = "ROGUE", sure = true },
    ["2v2|druid+rogue|priest+warlock"] = { t = "WARLOCK", sure = true },
    ["2v2|druid+rogue|rogue+rogue"] = { t = "ROGUE", sure = true },
    ["2v2|druid+rogue|shaman+warrior"] = { t = "SHAMAN", sure = true },
    ["2v2|mage+rogue|druid+hunter"] = { t = "HUNTER", sure = true },
    ["2v2|mage+rogue|druid+rogue"] = { t = "ROGUE", sure = true },
    ["2v2|mage+rogue|druid+warlock"] = { t = "DRUID", sure = true },
    ["2v2|mage+rogue|druid+warrior"] = { t = "DRUID", sure = true },
    ["2v2|mage+rogue|hunter+priest"] = { t = "HUNTER", sure = true },
    ["2v2|mage+rogue|mage+paladin"] = { t = "MAGE", sure = true },
    ["2v2|mage+rogue|mage+priest"] = { t = "PRIEST", sure = true },
    ["2v2|mage+rogue|mage+rogue"] = { t = "ROGUE", sure = true },
    ["2v2|mage+rogue|mage+warrior"] = { t = "MAGE", sure = true },
    ["2v2|mage+rogue|paladin+rogue"] = { t = "ROGUE", sure = true },
    ["2v2|mage+rogue|paladin+shaman"] = { t = "PALADIN", sure = true },
    ["2v2|mage+rogue|paladin+warlock"] = { t = "WARLOCK", sure = true },
    ["2v2|mage+rogue|paladin+warrior"] = { t = "WARRIOR", sure = true },
    ["2v2|mage+rogue|priest+rogue"] = { t = "PRIEST", sure = false },
    ["2v2|mage+rogue|priest+warlock"] = { t = "PRIEST", sure = true },
    ["2v2|mage+rogue|priest+warrior"] = { t = "PRIEST", sure = true },
    ["2v2|mage+rogue|rogue+rogue"] = { t = "ROGUE", sure = true },
    ["2v2|mage+rogue|rogue+warlock"] = { t = "WARLOCK", sure = true },
    ["2v2|mage+rogue|rogue+warrior"] = { t = "ROGUE", sure = true },
    ["2v2|mage+rogue|shaman+warlock"] = { t = "WARLOCK", sure = true },
    ["2v2|mage+rogue|shaman+warrior"] = { t = "SHAMAN", sure = true },
    ["2v2|priest+rogue|druid+hunter"] = { t = "DRUID", sure = true },
    ["2v2|priest+rogue|druid+mage"] = { t = "MAGE", sure = true },
    ["2v2|priest+rogue|druid+rogue"] = { t = "ROGUE", sure = true },
    ["2v2|priest+rogue|druid+warlock"] = { t = "DRUID", sure = true },
    ["2v2|priest+rogue|druid+warrior"] = { t = "DRUID", sure = true },
    ["2v2|priest+rogue|hunter+paladin"] = { t = "HUNTER", sure = true },
    ["2v2|priest+rogue|mage+paladin"] = { t = "MAGE", sure = true },
    ["2v2|priest+rogue|mage+priest"] = { t = "MAGE", sure = true },
    ["2v2|priest+rogue|mage+rogue"] = { t = "ROGUE", sure = true },
    ["2v2|priest+rogue|mage+warrior"] = { t = "MAGE", sure = true },
    ["2v2|priest+rogue|paladin+rogue"] = { t = "PALADIN", sure = true },
    ["2v2|priest+rogue|paladin+shaman"] = { t = "PALADIN", sure = true },
    ["2v2|priest+rogue|paladin+warlock"] = { t = "WARLOCK", sure = true },
    ["2v2|priest+rogue|paladin+warrior"] = { t = "WARRIOR", sure = true },
    ["2v2|priest+rogue|priest+rogue"] = { t = "PRIEST", sure = false },
    ["2v2|priest+rogue|priest+warlock"] = { t = "WARLOCK", sure = true },
    ["2v2|priest+rogue|rogue+rogue"] = { t = "ROGUE", sure = true },
    ["2v2|priest+rogue|rogue+warlock"] = { t = "WARLOCK", sure = true },
    ["2v2|priest+rogue|rogue+warrior"] = { t = "ROGUE", sure = true },
    ["2v2|priest+rogue|shaman+warlock"] = { t = "WARLOCK", sure = true },
    ["2v2|priest+rogue|shaman+warrior"] = { t = "WARRIOR", sure = true },
    ["2v2|rogue+rogue|druid+hunter"] = { t = "HUNTER", sure = true },
    ["2v2|rogue+rogue|druid+rogue"] = { t = "DRUID", sure = true },
    ["2v2|rogue+rogue|druid+warlock"] = { t = "DRUID", sure = true },
    ["2v2|rogue+rogue|druid+warrior"] = { t = "DRUID", sure = true },
    ["2v2|rogue+rogue|mage+priest"] = { t = "MAGE", sure = true },
    ["2v2|rogue+rogue|mage+rogue"] = { t = "MAGE", sure = true },
    ["2v2|rogue+rogue|paladin+shaman"] = { t = "SHAMAN", sure = true },
    ["2v2|rogue+rogue|paladin+warrior"] = { t = "WARRIOR", sure = true },
    ["2v2|rogue+rogue|priest+rogue"] = { t = "PRIEST", sure = true },
    ["2v2|rogue+rogue|priest+warlock"] = { t = "WARLOCK", sure = true },
    ["2v2|rogue+rogue|rogue+rogue"] = { t = "ROGUE", sure = true },
    ["2v2|rogue+rogue|shaman+warrior"] = { t = "SHAMAN", sure = true },
    ["2v2|rogue+warlock|druid+hunter"] = { t = "HUNTER", sure = true },
    ["2v2|rogue+warlock|druid+rogue"] = { t = "DRUID", sure = true },
    ["2v2|rogue+warlock|druid+warlock"] = { t = "DRUID", sure = true },
    ["2v2|rogue+warlock|druid+warrior"] = { t = "DRUID", sure = true },
    ["2v2|rogue+warlock|mage+priest"] = { t = "MAGE", sure = true },
    ["2v2|rogue+warlock|mage+rogue"] = { t = "MAGE", sure = true },
    ["2v2|rogue+warlock|paladin+shaman"] = { t = "SHAMAN", sure = true },
    ["2v2|rogue+warlock|paladin+warrior"] = { t = "WARRIOR", sure = true },
    ["2v2|rogue+warlock|priest+rogue"] = { t = "PRIEST", sure = true },
    ["2v2|rogue+warlock|priest+warlock"] = { t = "WARLOCK", sure = true },
    ["2v2|rogue+warlock|rogue+rogue"] = { t = "ROGUE", sure = true },
    ["2v2|rogue+warlock|shaman+warrior"] = { t = "SHAMAN", sure = true },
    ["3v3|druid+rogue+rogue|druid+rogue+warlock"] = { t = "DRUID", sure = true },
    ["3v3|druid+rogue+rogue|druid+warlock+warrior"] = { t = "WARLOCK", sure = true },
    ["3v3|druid+rogue+rogue|mage+priest+rogue"] = { t = "MAGE", sure = true },
    ["3v3|druid+rogue+rogue|mage+priest+warlock"] = { t = "MAGE", sure = true },
    ["3v3|druid+rogue+rogue|priest+rogue+warlock"] = { t = "PRIEST", sure = true },
    ["3v3|mage+priest+rogue|druid+hunter+priest"] = { t = "HUNTER", sure = true },
    ["3v3|mage+priest+rogue|druid+rogue+warlock"] = { t = "WARLOCK", sure = true },
    ["3v3|mage+priest+rogue|druid+warlock+warrior"] = { t = "WARLOCK", sure = true },
    ["3v3|mage+priest+rogue|mage+priest+rogue"] = { t = "MAGE", sure = true },
    ["3v3|mage+priest+rogue|mage+priest+shaman"] = { t = "MAGE", sure = true },
    ["3v3|mage+priest+rogue|mage+priest+warlock"] = { t = "MAGE", sure = true },
    ["3v3|mage+priest+rogue|mage+priest+warrior"] = { t = "MAGE", sure = true },
    ["3v3|mage+priest+rogue|priest+rogue+warlock"] = { t = "WARLOCK", sure = true },
    ["3v3|mage+priest+rogue|priest+shaman+warlock"] = { t = "PRIEST", sure = true },
}

-- Сколько матчапов скомпилировано (для /ac status и диагностики).
AC.KB_KILL_TARGETS_COUNT = 92
