-- ArenaCoach/Openers.lua
-- СГЕНЕРИРОВАНО tools/gen_addon_openers.py — не редактировать руками.
-- Источник: kb/drafts + kb/matchups (kill_target + секция Opener).
--
-- Тактический колаут на воротах. Ключ тот же, что у KillTargets.lua:
-- "<bracket>|<наши классы>|<классы врагов>", sorted+lowercase.
-- Значение: { c = "имя клипа без .ogg", t = "текст (для панели и /ac say)" }.
-- Нет ключа → фолбэк: «Бей <класс>!» из Voice.lua + угрозы (поведение 4.19).

local AC = ArenaCoach

AC.KB_OPENERS = {
    ["2v2|druid+rogue|druid+hunter"] = { c = "op_2v2_druid-rogue_druid-hunter", t = "Бей ханта! Степ, чип, кидни. Циклон — фейкай." },
    ["2v2|druid+rogue|druid+rogue"] = { c = "op_2v2_druid-rogue_druid-rogue", t = "Сап рогу, бей друида! Чип, кидни. Блайнд — тринка." },
    ["2v2|druid+rogue|druid+warlock"] = { c = "op_2v2_druid-rogue_druid-warlock", t = "Бей друида! Чип, кидни. Кик хил. Девор — фейкай." },
    ["2v2|druid+rogue|druid+warrior"] = { c = "op_2v2_druid-rogue_druid-warrior", t = "Сап вара, бей друида! Чип, хема, гадж, кидни." },
    ["2v2|druid+rogue|mage+priest"] = { c = "op_2v2_druid-rogue_mage-priest", t = "Сап приста, бей мага! Чип, кидни. Кик овцу. Бёрн — в лос." },
    ["2v2|druid+rogue|mage+rogue"] = { c = "op_2v2_druid-rogue_mage-rogue", t = "Сап рогу, бей мага! Чип, кидни. Кик овцу. Блайнд — тринка." },
    ["2v2|druid+rogue|paladin+shaman"] = { c = "op_2v2_druid-rogue_paladin-shaman", t = "Сап палу, бей шама! Чип, кидни. Кик хил. Крылья — тринка." },
    ["2v2|druid+rogue|paladin+warrior"] = { c = "op_2v2_druid-rogue_paladin-warrior", t = "Сап палу, бей вара! Чип, кидни. Бабл — не сливай." },
    ["2v2|druid+rogue|priest+rogue"] = { c = "op_2v2_druid-rogue_priest-rogue", t = "Сап приста, бей рогу! Чип, кидни. Жди саппресс." },
    ["2v2|druid+rogue|priest+warlock"] = { c = "op_2v2_druid-rogue_priest-warlock", t = "Сап приста, бей лока! Чип, кидни. Жди саппресс." },
    ["2v2|druid+rogue|rogue+rogue"] = { c = "op_2v2_druid-rogue_rogue-rogue", t = "Бей рогу! Чип, кидни. Блайнд — тринка." },
    ["2v2|druid+rogue|shaman+warrior"] = { c = "op_2v2_druid-rogue_shaman-warrior", t = "Сап вара, бей шама! Чип, кидни. Кик хил." },
    ["2v2|mage+rogue|druid+hunter"] = { c = "op_2v2_mage-rogue_druid-hunter", t = "Бей ханта! Гадж, кидни." },
    ["2v2|mage+rogue|druid+rogue"] = { c = "op_2v2_mage-rogue_druid-rogue", t = "Сап друида, бей рогу! Премед, чип, кидни." },
    ["2v2|mage+rogue|druid+warlock"] = { c = "op_2v2_mage-rogue_druid-warlock", t = "Бей друида! Премед, чип, шив, кидни." },
    ["2v2|mage+rogue|druid+warrior"] = { c = "op_2v2_mage-rogue_druid-warrior", t = "Бей друида! Ваниш, премед, гарота, эвис." },
    ["2v2|mage+rogue|mage+paladin"] = { c = "op_2v2_mage-rogue_mage-paladin", t = "Бей мага! Премед, чип, хема, кидни. Бабл — не сливай." },
    ["2v2|mage+rogue|mage+priest"] = { c = "op_2v2_mage-rogue_mage-priest", t = "Сап мага, бей приста! Премед, чип, кидни. Блок — не сливай." },
    ["2v2|mage+rogue|mage+rogue"] = { c = "op_2v2_mage-rogue_mage-rogue", t = "Сап мага, бей рогу! Степ, премед, чип, хема." },
    ["2v2|mage+rogue|mage+warrior"] = { c = "op_2v2_mage-rogue_mage-warrior", t = "Бей мага! Премед, чип, хема, кидни." },
    ["2v2|mage+rogue|paladin+rogue"] = { c = "op_2v2_mage-rogue_paladin-rogue", t = "Бей рогу! Чип, кидни. Бабл — не сливай." },
    ["2v2|mage+rogue|paladin+shaman"] = { c = "op_2v2_mage-rogue_paladin-shaman", t = "Овца шама, бей палу! Премед, чип, хема, кидни." },
    ["2v2|mage+rogue|paladin+warlock"] = { c = "op_2v2_mage-rogue_paladin-warlock", t = "Бей лока! Кс хил палы, шаттер-бёрст. Не сливай в бабл." },
    ["2v2|mage+rogue|paladin+warrior"] = { c = "op_2v2_mage-rogue_paladin-warrior", t = "Бей вара! Бабл — не сливай." },
    ["2v2|mage+rogue|priest+rogue"] = { c = "op_2v2_mage-rogue_priest-rogue", t = "Бей рогу! Премед, чип, хема, кидни." },
    ["2v2|mage+rogue|priest+warlock"] = { c = "op_2v2_mage-rogue_priest-warlock", t = "Бей приста! Премед, чип, кидни." },
    ["2v2|mage+rogue|rogue+rogue"] = { c = "op_2v2_mage-rogue_rogue-rogue", t = "Бей рогу! Премед, чип, кидни." },
    ["2v2|mage+rogue|rogue+warlock"] = { c = "op_2v2_mage-rogue_rogue-warlock", t = "Сап рогу, бей лока! Премед, чип, кидни. Блайнд — тринка." },
    ["2v2|mage+rogue|rogue+warrior"] = { c = "op_2v2_mage-rogue_rogue-warrior", t = "Бей рогу! Премед, чип, хема, кидни." },
    ["2v2|mage+rogue|shaman+warlock"] = { c = "op_2v2_mage-rogue_shaman-warlock", t = "Сап шама, бей лока! Чип, кидни." },
    ["2v2|mage+rogue|shaman+warrior"] = { c = "op_2v2_mage-rogue_shaman-warrior", t = "Бей шама! Премед, чип, хема, гадж." },
    ["2v2|priest+rogue|druid+hunter"] = { c = "op_2v2_priest-rogue_druid-hunter", t = "Бей друида! Премед, чип, хема, кидни." },
    ["2v2|priest+rogue|druid+mage"] = { c = "op_2v2_priest-rogue_druid-mage", t = "Бей мага! Циклон — фейкай." },
    ["2v2|priest+rogue|druid+rogue"] = { c = "op_2v2_priest-rogue_druid-rogue", t = "Сап друида, бей рогу! Степ, премед, чип." },
    ["2v2|priest+rogue|druid+warlock"] = { c = "op_2v2_priest-rogue_druid-warlock", t = "Бей друида! Чип, хема, гадж, кидни. Фир — в лос." },
    ["2v2|priest+rogue|druid+warrior"] = { c = "op_2v2_priest-rogue_druid-warrior", t = "Бей друида! Чип, хема, гадж, кидни." },
    ["2v2|priest+rogue|hunter+paladin"] = { c = "op_2v2_priest-rogue_hunter-paladin", t = "Бей ханта! Гарота, чип, кидни. Вайпер — в лос." },
    ["2v2|priest+rogue|mage+paladin"] = { c = "op_2v2_priest-rogue_mage-paladin", t = "Бей мага! Чип, кидни. Бабл — не сливай." },
    ["2v2|priest+rogue|mage+priest"] = { c = "op_2v2_priest-rogue_mage-priest", t = "Бей мага! Премед, чип, кидни. Бёрн — в лос." },
    ["2v2|priest+rogue|mage+rogue"] = { c = "op_2v2_priest-rogue_mage-rogue", t = "Бей рогу! Премед, чип, хема." },
    ["2v2|priest+rogue|mage+warrior"] = { c = "op_2v2_priest-rogue_mage-warrior", t = "Сап вара, бей мага! Чип, кидни." },
    ["2v2|priest+rogue|paladin+rogue"] = { c = "op_2v2_priest-rogue_paladin-rogue", t = "Сап рогу, бей палу! Блайнд — тринка." },
    ["2v2|priest+rogue|paladin+shaman"] = { c = "op_2v2_priest-rogue_paladin-shaman", t = "Бей палу! Бёрн ману, вунды на рета." },
    ["2v2|priest+rogue|paladin+warlock"] = { c = "op_2v2_priest-rogue_paladin-warlock", t = "Сап палу, бей лока! Бёрн палу в оом." },
    ["2v2|priest+rogue|paladin+warrior"] = { c = "op_2v2_priest-rogue_paladin-warrior", t = "Бей вара! Бабл — не сливай." },
    ["2v2|priest+rogue|priest+rogue"] = { c = "op_2v2_priest-rogue_priest-rogue", t = "Бей рогу! Гадж, кидни." },
    ["2v2|priest+rogue|priest+warlock"] = { c = "op_2v2_priest-rogue_priest-warlock", t = "Сап приста, бей лока! Чип, гадж, кидни. Держи вунды." },
    ["2v2|priest+rogue|rogue+rogue"] = { c = "op_2v2_priest-rogue_rogue-rogue", t = "Бей рогу! Блайнд — тринка." },
    ["2v2|priest+rogue|rogue+warlock"] = { c = "op_2v2_priest-rogue_rogue-warlock", t = "Сап рогу, бей лока! Чип, гадж. Блайнд — тринка." },
    ["2v2|priest+rogue|rogue+warrior"] = { c = "op_2v2_priest-rogue_rogue-warrior", t = "Бей рогу! Премед, чип, хема, кидни." },
    ["2v2|priest+rogue|shaman+warlock"] = { c = "op_2v2_priest-rogue_shaman-warlock", t = "Сап шама, бей лока! Чип, хема, кидни." },
    ["2v2|priest+rogue|shaman+warrior"] = { c = "op_2v2_priest-rogue_shaman-warrior", t = "Бей вара! Чип, кидни." },
    ["2v2|rogue+warlock|druid+hunter"] = { c = "op_2v2_rogue-warlock_druid-hunter", t = "Бей ханта! Чип, кидни. Циклон — фейкай." },
    ["2v2|rogue+warlock|druid+rogue"] = { c = "op_2v2_rogue-warlock_druid-rogue", t = "Сап рогу, бей друида! Чип, кидни. Блайнд — тринка." },
    ["2v2|rogue+warlock|druid+warlock"] = { c = "op_2v2_rogue-warlock_druid-warlock", t = "Бей друида! Чип, кидни. Девор — фейкай." },
    ["2v2|rogue+warlock|druid+warrior"] = { c = "op_2v2_rogue-warlock_druid-warrior", t = "Бей друида! Чип, кидни." },
    ["2v2|rogue+warlock|mage+priest"] = { c = "op_2v2_rogue-warlock_mage-priest", t = "Бей мага! Чип, кидни. Жди саппресс." },
    ["2v2|rogue+warlock|mage+rogue"] = { c = "op_2v2_rogue-warlock_mage-rogue", t = "Сап рогу, бей мага! Премед, чип, кидни. Блайнд — тринка." },
    ["2v2|rogue+warlock|paladin+shaman"] = { c = "op_2v2_rogue-warlock_paladin-shaman", t = "Бей шама! Чип, кидни. Бабл — не сливай." },
    ["2v2|rogue+warlock|paladin+warrior"] = { c = "op_2v2_rogue-warlock_paladin-warrior", t = "Бей вара! Премед, чип, кидни. Бабл — не сливай." },
    ["2v2|rogue+warlock|priest+rogue"] = { c = "op_2v2_rogue-warlock_priest-rogue", t = "Сап рогу, бей приста! Чип, кидни. Блайнд — тринка." },
    ["2v2|rogue+warlock|priest+warlock"] = { c = "op_2v2_rogue-warlock_priest-warlock", t = "Сап приста, бей лока! Чип, кидни. Бёрн — в лос." },
    ["2v2|rogue+warlock|rogue+rogue"] = { c = "op_2v2_rogue-warlock_rogue-rogue", t = "Бей рогу! Чип, кидни. Блайнд — тринка." },
    ["2v2|rogue+warlock|shaman+warrior"] = { c = "op_2v2_rogue-warlock_shaman-warrior", t = "Бей шама! Чип, кидни." },
    ["3v3|druid+rogue+rogue|druid+rogue+warlock"] = { c = "op_3v3_druid-rogue-rogue_druid-rogue-warlock", t = "Сап рогу, бей друида! Чип, кидни. Фир — в лос." },
    ["3v3|druid+rogue+rogue|druid+warlock+warrior"] = { c = "op_3v3_druid-rogue-rogue_druid-warlock-warrior", t = "Бей лока! Чип, кидни. Циклон — фейкай." },
    ["3v3|druid+rogue+rogue|mage+priest+rogue"] = { c = "op_3v3_druid-rogue-rogue_mage-priest-rogue", t = "Сап приста, бей мага! Бёрн — в лос." },
    ["3v3|druid+rogue+rogue|mage+priest+warlock"] = { c = "op_3v3_druid-rogue-rogue_mage-priest-warlock", t = "Бей мага! Чип, кидни. Бёрн — в лос." },
    ["3v3|druid+rogue+rogue|priest+rogue+warlock"] = { c = "op_3v3_druid-rogue-rogue_priest-rogue-warlock", t = "Сап рогу, бей приста! Чип, кидни. Фир — в лос." },
    ["3v3|mage+priest+rogue|druid+hunter+priest"] = { c = "op_3v3_mage-priest-rogue_druid-hunter-priest", t = "Сап друида, бей ханта! Чип, кидни. Бёрн — в лос." },
    ["3v3|mage+priest+rogue|druid+rogue+warlock"] = { c = "op_3v3_mage-priest-rogue_druid-rogue-warlock", t = "Сап друида, бей лока! Чип, кидни. Циклон — фейкай." },
    ["3v3|mage+priest+rogue|druid+warlock+warrior"] = { c = "op_3v3_mage-priest-rogue_druid-warlock-warrior", t = "Сап друида, бей лока! Циклон — фейкай." },
    ["3v3|mage+priest+rogue|mage+priest+rogue"] = { c = "op_3v3_mage-priest-rogue_mage-priest-rogue", t = "Бей мага! Премед, чип, кидни. Жди саппресс." },
    ["3v3|mage+priest+rogue|mage+priest+shaman"] = { c = "op_3v3_mage-priest-rogue_mage-priest-shaman", t = "Бей мага! Чип, кидни. Бёрн — в лос." },
    ["3v3|mage+priest+rogue|mage+priest+warlock"] = { c = "op_3v3_mage-priest-rogue_mage-priest-warlock", t = "Бей мага! Премед, чип, кидни. Жди саппресс." },
    ["3v3|mage+priest+rogue|mage+priest+warrior"] = { c = "op_3v3_mage-priest-rogue_mage-priest-warrior", t = "Бей мага! Чип, кидни. Бёрн — в лос." },
    ["3v3|mage+priest+rogue|priest+rogue+warlock"] = { c = "op_3v3_mage-priest-rogue_priest-rogue-warlock", t = "Бей лока! Премед, чип, кидни. Бёрн — в лос." },
    ["3v3|mage+priest+rogue|priest+shaman+warlock"] = { c = "op_3v3_mage-priest-rogue_priest-shaman-warlock", t = "Сап шама, бей приста! Чип, кидни. Фир — в лос." },
}

AC.KB_OPENERS_COUNT = 78
